### PR TITLE
New GIDCollection print

### PR DESCRIPTION
**Pull request by stinebuu**
Change the way we print `GIDCollection`s, see #8 for details.

Printing a primitive `GIDCollection` without metadata will look like:
```
GIDCollection(metadata=None model=iaf_psc_alpha, size=5, (1..5))
```
Printing a layer will look like:
```
GIDCollection(metadata=spatial model=iaf_psc_alpha, size=25, (54..78))
```
Printing a sliced composite with more than 7 parts will look like:
```
GIDCollection(metadata=None, size=17:
              model=iaf_psc_alpha, size=3, (1..{2}..5);
              model=iaf_psc_delta, size=1, (7);
              model=iaf_psc_exp, size=1, (9);
              ..
              model=spike_detector, size=1, (19);
              model=iaf_psc_alpha, size=2, (21, 23);
              model=iaf_cond_alpha, size=5, (45..{2}..53))
```

### CODE REVIEW

**Comment by heplesser** [comment]
Nice, but I am wondering a bit about the stepping notation
```
 model=iaf_psc_alpha, size=3, (1..{2}..5);
```
Do we need the curly braces? And maybe we could make the notation even more consistent like this:
```
 model=iaf_psc_alpha, size=3, gids=1..2..5;
 model=iaf_psc_alpha, size=3, gids=6..8;
 model=iaf_psc_alpha, size=1, gids=9;
```
and similarly for non-composite.

**Comment by hakonsbm** [comment]
@heplesser My idea when adding the curly braces to the stepping notation was to separate number of steps from GIDs, because I thought writing `(1..2..5)` could look like it means
```
(GID=1 [some GIDs] GID=2 [some GIDs] GID=5)
```

**Comment by heplesser** [comment]
Maybe we should have a little poll on NEST User? I also thought about the Python notation `1:5:2`, but that is confusing, since in real Python that is on 1 and 3, 5 is excluded.

**Comment by stinebuu** [comment]
@heplesser I like the notation of `gids=6..8` for consistency. Concerning the stepping, would
```
model=iaf_psc_alpha, size=3, gids=1..5, step=2;
```
be an option?

**Comment by heplesser** [comment]
I am not totally happy with the notation, since it puts `step` at the same level as `gids`. How about

```
model=iaf_psc_alpha, size=3, gids=1..5 [step 2];
```

Should we have a discussion and vote on Monday?

**Comment by stinebuu** [comment]
@heplesser Discussion and vote sounds good!

**Comment by stinebuu** [comment]
From NEST VC: Use `first`, `last` and `step`:
`model=iaf_psc_alpha, size=3, first=1, last=5, step=2;`

Also, the first `size` variable from the sliced composite above makes it look like there are 17 parts of the composite, not 17 GIDs.

**Comment by stinebuu** [comment]
With 97e33f0 we will have the following

Printing a primitive `GIDCollection` without `metadata`:
```
GIDCollection(metadata=None, model=iaf_psc_alpha, size=5, first=1, last=5)
```
Printing a composite `GIDCollection` without any slicing:
```
GIDCollection(metadata=None,
              model=iaf_psc_alpha, size=5, first=1, last=5;
              model=iaf_psc_delta, size=3, first=6, last=8;
              model=iaf_psc_exp, size=1, first=9;
              model=iaf_cond_alpha, size=7, first=10, last=16;
              model=poisson_generator, size=1, first=17;
              model=spike_detector, size=3, first=18, last=20)
```
Printing a sliced composite with more than 7 parts:
```
GIDCollection(metadata=None,
              model=iaf_psc_alpha, size=3, first=1, last=5, step=2;
              model=iaf_psc_delta, size=1, first=7, last=7;
              model=iaf_psc_exp, size=1, first=9, last=9;
              ..
              model=spike_detector, size=1, first=19, last=19;
              model=iaf_psc_alpha, size=2, first=21, last=23, step=2;
              model=iaf_cond_alpha, size=5, first=45, last=53, step=2)
```
Printing a layer:
```
GIDCollection(metadata=spatial, model=iaf_psc_alpha, size=25, first=54, last=78)
```

@heplesser @hakonsbm what do you think?

**Comment by stinebuu** [comment]
@heplesser @hakonsbm as discussed, I have now removed the partitioning when a composite have more than 7 parts.

**Comment by heplesser** [comment]
@stinebuu So what happens now if you print a GC with more than seven parts?

**Comment by stinebuu** [comment]
@heplesser You are shown all the parts of the GIDCollection, like this, where we have a composite gc which is sliced and consists of 8 primitives:
```
GIDCollection(metadata=None,
              model=iaf_psc_alpha, size=3, first=1, last=5, step=2;
              model=iaf_psc_delta, size=1, first=7, last=7;
              model=iaf_psc_exp, size=1, first=9, last=9;
              model=iaf_cond_alpha, size=3, first=11, last=15, step=2;
              model=poisson_generator, size=1, first=17, last=17;
              model=spike_detector, size=1, first=19, last=19;
              model=iaf_psc_alpha, size=2, first=21, last=23, step=2;
              model=iaf_cond_alpha, size=5, first=45, last=53, step=2)
```

**Comment by heplesser** [comment]
OK.


> On 16 Apr 2019, at 13:19, Stine Brekke Vennemo <notifications@github.com> wrote:
> 
> @heplesser You are shown all the parts of the GIDCollection, like this, where we have a composite gc which is sliced and consists of 8 primitives:
> 
> GIDCollection(metadata=None,
>               model=iaf_psc_alpha, size=3, first=1, last=5, step=2;
>               model=iaf_psc_delta, size=1, first=7, last=7;
>               model=iaf_psc_exp, size=1, first=9, last=9;
>               model=iaf_cond_alpha, size=3, first=11, last=15, step=2;
>               model=poisson_generator, size=1, first=17, last=17;
>               model=spike_detector, size=1, first=19, last=19;
>               model=iaf_psc_alpha, size=2, first=21, last=23, step=2;
>               model=iaf_cond_alpha, size=5, first=45, last=53, step=2)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--

Prof. Dr. Hans Ekkehard Plesser
Head, Data Science Section

Faculty of Science and Technology
Norwegian University of Life Sciences
PO Box 5003, 1432 Aas, Norway

Phone +47 6723 1560
Email hans.ekkehard.plesser@nmbu.no
Home  http://arken.nmbu.no/~plesser

**Pull request merged**
